name: pdf_previewer
description: Provides a way to generate previews of selected pages in a PDF file from a provided path. 
author: Miguel Ruivo <miguelpruivo@outlook.com>
homepage: https://github.com/miguelpruivo/flutter_pdf_previewer
version: 0.1.3+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.5
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.mr.flutter.plugin.pdfpreview.pdfpreviewer
    pluginClass: PdfPreviewerPlugin

